"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import HeaderLoggedIn from "./components/headerLoggedIn";
import React,{useState,useEffect} from 'react';

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Agodel",
//   description: "Generated by create next app",
// };



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isLoggedIn, setIsLoggedIn] =
    useState(false);
  useEffect(() => {
    // Check if user is logged in when component mounts
    console.log(
      localStorage.getItem("login")
    );
    console.log(
      localStorage.getItem("role")
    ); // Log the value of "login" from localStorage
    if (!(localStorage.getItem("login") ===null)) {
      setIsLoggedIn(true);
    }
  }, []);
  console.log(isLoggedIn);
  return (
    <html lang="en">
      <body className={inter.className}>
      <div>
      {isLoggedIn && <HeaderLoggedIn />}
      {!isLoggedIn && <Header />}
      {children}
    </div>
        </body>
    </html>
    
  );
}
